### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [chinsun9/chinsun9.github.io#2]
Hi ,

url : https://github.com/chinsun9/chinsun9.github.io/blob/9dc57f0185b02902d17dea9978a81ef723c76889/content.json

![image](https://user-images.githubusercontent.com/46863888/104559757-89d76f80-564d-11eb-8ab1-a373a022e7c1.png)

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by chinsun9** [comment]
That's not my secret. It's just  example text.

But thanks

**Comment by shaybenb** [comment]
ok 
sorry my bot open it automticly
